### ISSUE TITLE
JSON-formatted copy to clipboard

### ISSUE THREAD

**Issue by fluffysquirrels** [anaghvj/OpenedTabs#1]
The copy tabs as text to clipboard feature is very useful, but I want to customise the format to put into my personal organiser. If it were formatted as JSON it would be very easy to manipulate with existing tools like jq.

As a workaround, I could write an awk script or something to reformat the data.

Love the project! I've been looking for open source tab management that I can use with my personal organisation for a while.

**Comment by anaghvj** [comment]
Added the json copy button.

**Comment by anaghvj** [comment]
# 6423b62a2000e376bc87de3e42fcb88c6921d9b1
